### ISSUE TITLE
スタイル作成

### ISSUE THREAD

**Issue by yui-szk** [kanaru-ssk/frontend-book#3]
## 概要
- ヘッダー
- フッター
- メニューボタン
- 基本スタイル（h1, h2...）

**Comment by kanaru-ssk** [comment]
以下を使用してスタイル最小限のスタイルを当てる。
https://tailwindcss.com/docs/typography-plugin

prismを使用してシンタックスハイライトを当てる

**Comment by kanaru-ssk** [comment]
**メモ**
`tailwindcss/typegraphy`は導入済み。

残り
- シンタックスハイライト追加
- ヘッダー・フッターなどのスタイリング

**Comment by kanaru-ssk** [comment]
参考サイト
- [Next.js Document](https://nextjs.org/docs/app)
- [Rust Book](https://doc.rust-lang.org/book/)
- [tailwindcss Document](https://tailwindcss.com/docs/installation)
- [React Document](https://react.dev/learn)
